USE ecom;
ALTER TABLE shipping_info
  ADD COLUMN IF NOT EXISTS service VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS tracking_number VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS tracking_url VARCHAR(600) NULL,
  ADD COLUMN IF NOT EXISTS shipping_error VARCHAR(255) NULL;